# This image is built with the command below:
#
# ```
# docker build -f .gitpod/Dockerfile -t willdurand/gitpod-firefox-dev .
# ```
image: willdurand/gitpod-firefox-dev:latest

tasks:
  - name: bootstrap
    before: |
      # Everything below will be executed every time we open Gitpod (either any
      # existing workspace OR a completely new one).
      "$GITPOD_REPO_ROOT/.gitpod/scripts/bootstrap-before.sh"

    init: |
      # Everything below will be executed when we create a new workspace.
      "$GITPOD_REPO_ROOT/.gitpod/scripts/bootstrap-init.sh"

    command: |
      cd "$GITPOD_REPO_ROOT/mozilla-unified"
      # Run Firefox
      ./mach run

ports:
  # mochitest
  - port: 2828
    onOpen: ignore
# mochitest
  - port: 4443
    onOpen: ignore
# VNC
  - port: 5900
    onOpen: ignore
# VNC (web view)
# This is the port you should be using to interact with Firefox. It is a bit
# annoying to have it open at every workspace startup, though, so it is now
# ignored.
  - port: 6080
    onOpen: ignore
# mochitest
  - port: 8888
    onOpen: ignore
# mochitest
  - port: 9988
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ecmel.vscode-html-css
    - esbenp.prettier-vscode
